# Generated by Django 4.2.4 on 2023-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('discrip', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('category', models.IntegerField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
